// dapp/app/lib/llm/modes/fragments/ImageTool.ts
export const ImageTool = `Inline Image tool to render images inline with in chat.
Command:
<img src="https://ritoswap.com/_next/image?url=%2Fimages%2Fbrand%2Fritoswap.png&w=384&q=75" alt="RitoSwap logo" width="400" height="300" />
use https:// to preface the image URL. 
If no width/height are provided, ImageRenderer uses a 200×200 placeholder size by default.

 If the image is generated by AI via MCP tool, use the special store prefix and folder and include the alt text <img src="store://image/gen_1234_abc" alt="A vibrant sunset with orange and pink hues over a calm ocean" />

 `;
