// dapp/scripts/codegen/generate-presenters-index.ts
// Run with: pnpm codegen:presenters
// Purpose: generate components/.../catalog/generated-presenters.ts

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

// ESM-safe __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const presentersDir = path.resolve(
  __dirname,
  '../../components/chatBot/ToolActivity/catalog/presenters'
);

const relImportToGenerated = (absPath: string) => {
  const generatedDir = path.resolve(
    __dirname,
    '../../components/chatBot/ToolActivity/catalog'
  );
  // POSIX-style for import specifiers
  return (
    './' +
    path.posix
      .normalize(path.relative(generatedDir, absPath).replace(/\\/g, '/'))
      .replace(/^\.\//, '')
      .replace(/\.ts$/, '')
  );
};

function sanitizeVar(name: string) {
  return name.replace(/[^a-zA-Z0-9_$]/g, '_');
}

function generate() {
  if (!fs.existsSync(presentersDir)) {
    fs.mkdirSync(presentersDir, { recursive: true });
  }

  const files = fs
    .readdirSync(presentersDir)
    .filter((f) => f.endsWith('.presenter.ts'));

  const imports: string[] = [];
  const entries: string[] = [];

  files.forEach((file, idx) => {
    const abs = path.resolve(presentersDir, file);
    const rel = relImportToGenerated(abs);
    const varName = 'p' + idx + '_' + sanitizeVar(file.replace(/\.ts$/, ''));
    imports.push(`import * as ${varName} from '${rel}';`);
    // Use the module's declared toolName (runtime) instead of the filename
    entries.push(`  [${varName}.presenter.toolName as ToolName]: ${varName}.presenter`);
  });

  const out = `// AUTO-GENERATED. DO NOT EDIT.
// Generated by dapp/scripts/codegen/generate-presenters-index.ts

import type { ToolChipPresenter } from './types';
import type { ToolName } from '@lib/mcp/generated/tool-catalog-types';

${imports.join('\n')}

export const presenters = {
${entries.join(',\n')}
} as Partial<Record<ToolName, ToolChipPresenter<ToolName>>>;
`;

  const dest = path.resolve(
    __dirname,
    '../../components/chatBot/ToolActivity/catalog/generated-presenters.ts'
  );
  fs.writeFileSync(dest, out, 'utf8');
  console.log(`[codegen] Wrote ${dest}`);
}

generate();
