// AUTO-GENERATED. DO NOT EDIT.
// Generated by dapp/scripts/codegen/generate-presenters-index.ts

import type { ToolChipPresenter } from './types';
import type { ToolName } from '@lib/mcp/generated/tool-catalog-types';

import * as p0_agent_rap_verse_presenter from './presenters/agent_rap_verse.presenter';
import * as p1_eth_balance_presenter from './presenters/eth_balance.presenter';
import * as p2_generate_image_with_alt_presenter from './presenters/generate_image_with_alt.presenter';
import * as p3_keynft_manage_presenter from './presenters/keynft_manage.presenter';
import * as p4_keynft_read_presenter from './presenters/keynft_read.presenter';
import * as p5_keynft_used_count_presenter from './presenters/keynft_used_count.presenter';
import * as p6_mark_key_used_presenter from './presenters/mark_key_used.presenter';
import * as p7_pinecone_search_presenter from './presenters/pinecone_search.presenter';
import * as p8_send_crypto_presenter from './presenters/send_crypto.presenter';
import * as p9_send_crypto_agent_presenter from './presenters/send_crypto_agent.presenter';

export const presenters = {
  [p0_agent_rap_verse_presenter.presenter.toolName as ToolName]: p0_agent_rap_verse_presenter.presenter,
  [p1_eth_balance_presenter.presenter.toolName as ToolName]: p1_eth_balance_presenter.presenter,
  [p2_generate_image_with_alt_presenter.presenter.toolName as ToolName]: p2_generate_image_with_alt_presenter.presenter,
  [p3_keynft_manage_presenter.presenter.toolName as ToolName]: p3_keynft_manage_presenter.presenter,
  [p4_keynft_read_presenter.presenter.toolName as ToolName]: p4_keynft_read_presenter.presenter,
  [p5_keynft_used_count_presenter.presenter.toolName as ToolName]: p5_keynft_used_count_presenter.presenter,
  [p6_mark_key_used_presenter.presenter.toolName as ToolName]: p6_mark_key_used_presenter.presenter,
  [p7_pinecone_search_presenter.presenter.toolName as ToolName]: p7_pinecone_search_presenter.presenter,
  [p8_send_crypto_presenter.presenter.toolName as ToolName]: p8_send_crypto_presenter.presenter,
  [p9_send_crypto_agent_presenter.presenter.toolName as ToolName]: p9_send_crypto_agent_presenter.presenter
} as Partial<Record<ToolName, ToolChipPresenter<ToolName>>>;
